# Site metadata
site_name: After Effects Expression Reference
site_url: https://ae-expressions.docsforadobe.dev/
repo_url: https://github.com/docsforadobe/after-effects-expression-reference/
repo_name: "after-effects-expression-reference"

# Customize navigation
nav:
    - Home: index.md
    - Introduction:
        - Changelog: changelog.md
        - Resources: resources.md
        - Examples: examples.md
    - General:
        - Global: global.md
        - Time Conversion: time-conversion.md
        - Vector Math: vector-math.md
        - Random Numbers: random-numbers.md
        - Interpolation: interpolation.md
        - Color Conversion: color-conversion.md
        - Other Math: other-math.md
    - Objects:
        - Project: project.md
        - Comp: comp.md
        - Footage: footage.md
        - Camera: camera.md
        - Light: light.md
        - Group: group.md
        - Effect: effect.md
        - Mask: mask.md
        - Property: property.md
        - Path Property: path-property.md
        - Key: key.md
        - MarkerKey: markerkey.md
    - Layer:
        - Layer Sub-objects: layer-sub.md
        - Layer General: layer-general.md
        - Layer Properties: layer-properties.md
        - Layer Space Transforms: layer-space.md
        - Layer 3D: layer-threed.md
    - Text:
        - Text: text.md
        - Source Text: text-sourcetext.md
        - Text Style: text-style.md


# Do not touch below-- shared for all docs

copyright: All content is copyright Adobe Systems Incorporated.

extra:
    homepage: https://docsforadobe.dev

theme:
    name: material
    custom_dir: overrides
    features:
        - announce.dismiss
        - content.action.edit
        - content.action.view
        - search.highlight
        - search.suggest
        - toc.follow
    palette:
        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          primary: black
          scheme: slate
          toggle:
              icon: material/brightness-4
              name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          primary: white
          scheme: default
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

extra_css:
    # CSS shared between the whole org
    - https://docsforadobe.dev/_global/global.css
    - https://docsforadobe.dev/_global/global-syntax-highlight.css

    # CSS specific to this file
    - _static/extra.css

markdown_extensions:
    - admonition
    - pymdownx.superfences
    - toc:
        title: Page Contents
        permalink: true
        toc_depth: 3

plugins:
    - git-revision-date-localized
    - search:
        separator: '[\s\-,\.:!=\[\]()"/]+'

    # Note: print-site must be last!
    - print-site:
        add_cover_page: true
        add_print_site_banner: true
        cover_page_template: "overrides/templates/print_site_cover_page.tpl"
        print_page_title: "Offline Docs"
        print_site_banner_template: "overrides/templates/print_site_banner.tpl"
